### ISSUE TITLE
Gen 4 backplate

### ISSUE THREAD

**Issue by GCUGrayArea** [knack-69/PVS-69#3]
I can't find the file for the Gen 4 bridge backplate, and it definitely doesn't look like the Gen 3 will fit. Is this omitted or did this become unnecessary on the Gen 4 with the battery compartment removed? The readme for the Foxtrot is not clear on this.

**Comment by knack-tactical** [comment]
With the FOXTROT Gen4 bridge, there is the [bridge body](https://github.com/knack-tactical/PVS-69/blob/main/Gen3%20FOXTROT/STL/FOXTROT%20Gen4%20Bridge%20Body.stl) and the [frontplate](https://github.com/knack-tactical/PVS-69/blob/main/Gen3%20FOXTROT/STL/FOXTROT%20Gen4%20Bridge%20Frontplate.stl), which was switched to as it makes assembly easier compared to a backplate.
